!!python/object/apply:collections.OrderedDict
- - - type
    - TEMPLATE
  - - uuid
    - f5bb0778-524b-11ea-819c-02420a00070b
  - - name
    - '[ISAN] CC Rabbit'
  - - description
    - ''
  - - thumbnail
    - ''
  - - prj_owner
    - '1'
  - - creation_date
    - '2020-02-18 12:41:18.692'
  - - last_change_date
    - '2020-02-21 09:58:45.498'
  - - workbench
    - 001dd1f0-e3f5-4695-8e26-e3dfd82dda8e:
        inputNodes: []
        inputs: {}
        key: simcore/services/frontend/file-picker
        label: File Picker
        outputs:
          outFile:
            dataset: f5bb0778-524b-11ea-819c-02420a00070b
            label: initial_WTstates_Rabbit.txt
            path: f5bb0778-524b-11ea-819c-02420a00070b/001dd1f0-e3f5-4695-8e26-e3dfd82dda8e/initial_WTstates_Rabbit.txt
            store: 0
        position:
          x: 31
          y: 27
        progress: 100
        thumbnail: ''
        version: 1.0.0
      27d897b6-52ae-4aa9-afb3-12fbc8d2891e:
        inputNodes:
        - 001dd1f0-e3f5-4695-8e26-e3dfd82dda8e
        inputs:
          GKr: 1
          Homogeneity: homogeneous
          Na: 0
          TargetHeartRatePhase1: 60
          TargetHeartRatePhase2: 150
          TargetHeartRatePhase3: 60
          TotalSimulationTime: 300
          cAMKII: WT
          initialWTStates:
            nodeUuid: 001dd1f0-e3f5-4695-8e26-e3dfd82dda8e
            output: outFile
          num_threads: 2
          tissue_size_tl: 165
          tissue_size_tw: 165
        key: simcore/services/comp/rabbit-ss-0d-cardiac-model
        label: Rabbit SS 0D cardiac model
        position:
          x: 305
          y: 26
        thumbnail: ''
        version: 1.0.0
      4f7f01dc-825d-4e42-99e3-78697d4de731:
        inputNodes:
        - 6fe7f438-630b-429c-8d06-c036c2779cb2
        inputs:
          GKr: 1
          Homogeneity: homogeneous
          Na: 0
          TargetHeartRatePhase1: 60
          TargetHeartRatePhase2: 150
          TargetHeartRatePhase3: 60
          TotalSimulationTime: 10
          cAMKII: WT
          input_from_1d:
            nodeUuid: 6fe7f438-630b-429c-8d06-c036c2779cb2
            output: output_4
          num_threads: 2
          tissue_size_tl: 65
          tissue_size_tw: 65
        key: simcore/services/comp/rabbit-ss-2d-cardiac-model
        label: Rabbit SS 2D cardiac model
        position:
          x: 510
          y: 320
        thumbnail: ''
        version: 1.0.0
      52f7f296-9697-4c63-bfed-cd36694afd67:
        inputNodes:
        - 4f7f01dc-825d-4e42-99e3-78697d4de731
        inputs:
          ap:
            nodeUuid: 4f7f01dc-825d-4e42-99e3-78697d4de731
            output: output_1
        key: simcore/services/dynamic/cc-2d-viewer
        label: 2D cardiac model viewer
        position:
          x: 741
          y: 320
        thumbnail: ''
        version: 3.0.3
      6fe7f438-630b-429c-8d06-c036c2779cb2:
        inputNodes:
        - 001dd1f0-e3f5-4695-8e26-e3dfd82dda8e
        inputs:
          GKr: 1
          Homogeneity: homogeneous
          Na: 0
          TargetHeartRatePhase1: 60
          TargetHeartRatePhase2: 150
          TargetHeartRatePhase3: 60
          TotalSimulationTime: 300
          cAMKII: WT
          initialWTStates:
            nodeUuid: 001dd1f0-e3f5-4695-8e26-e3dfd82dda8e
            output: outFile
          num_threads: 2
          tissue_size_tl: 165
          tissue_size_tw: 165
        key: simcore/services/comp/rabbit-ss-1d-cardiac-model
        label: Rabbit SS 1D cardiac model
        position:
          x: 307
          y: 197
        thumbnail: ''
        version: 1.0.0
      7b103fe1-5650-4c96-add1-53927a30f7bb:
        inputNodes:
        - 27d897b6-52ae-4aa9-afb3-12fbc8d2891e
        inputs:
          vm1Hz:
            nodeUuid: 27d897b6-52ae-4aa9-afb3-12fbc8d2891e
            output: vm1Hz
        key: simcore/services/dynamic/cc-0d-viewer
        label: 0D cardiac model viewer
        position:
          x: 730
          y: 26
        thumbnail: ''
        version: 3.0.4
      e192edf5-bb7f-45f4-a47d-8970bc784cf8:
        inputNodes:
        - 6fe7f438-630b-429c-8d06-c036c2779cb2
        inputs:
          APs:
            nodeUuid: 6fe7f438-630b-429c-8d06-c036c2779cb2
            output: output_2
          ECGs:
            nodeUuid: 6fe7f438-630b-429c-8d06-c036c2779cb2
            output: output_1
        key: simcore/services/dynamic/cc-1d-viewer
        label: 1D cardiac model viewer
        position:
          x: 733
          y: 199
        thumbnail: ''
        version: 3.0.3
  - - published
    - '1'
